version: "3.9"

services:
    backend:
        command: python3 manage.py runserver 0.0.0.0:8080
        build:
            context: ./backend
            dockerfile: Dockerfile
        env_file:
            - local.env
        ports:
            - "8080:8080"
        volumes:
            - ./backend:/opt/io
        depends_on: 
            - db
    db:
        image: postgres:13.3
        env_file:
            - local.env
        volumes:
            - ./data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
    web:
        build: ./frontend
        ports:
            - 5555:80
        depends_on:
            - db
            - backend